import { type AgentPageContent } from "@/app/shared/agent-page-content"

// Workaround for next/image choking on these for some reason
import hero from "/public/heroes/agent-reviewer.png"

// Re-export for convenience
export type { AgentPageContent }

export const content: AgentPageContent = {
	agentName: "PR Reviewer",
	hero: {
		icon: "GitPullRequest",
		heading: "Code reviews that catch what other AI tools (and most humans) miss.",
		paragraphs: [
			"Run-of-the-mill, token-saving AI code review tools will surely catch syntax errors and style issues, but they'll usually miss the bugs that actually matter: logic flaws, security vulnerabilities, and misunderstood requirements.",
			"Roo Code's PR Reviewer uses advanced reasoning models and full repository context to find the issues that slip through—before they reach production.",
		],
		image: {
			url: hero.src,
			width: 800,
			height: 474,
			alt: "Example of a code review generated by Roo Code PR Reviewer",
		},
		crossAgentLink: {
			text: "Works great with",
			links: [
				{
					text: "PR Fixer Agent",
					href: "/pr-fixer",
					icon: "Wrench",
				},
			],
		},
		cta: {
			buttonText: "Start 14-day Free Trial",
			disclaimer: "(cancel anytime)",
		},
	},
	howItWorks: {
		heading: "How It Works",
		steps: [
			{
				title: "1. Connect Your Repository",
				description:
					"Link your GitHub repository and configure which branches and pull requests should be reviewed.",
				icon: "GitPullRequest",
			},
			{
				title: "2. Add Your API Key",
				description:
					"Provide your AI provider API key and set your review preferences, custom rules, and quality standards.",
				icon: "Key",
			},
			{
				title: "3. Get Review Comments",
				description:
					"Every pull request gets detailed GitHub comments in minutes from a Roo Code agent highlighting issues and suggesting improvements.",
				icon: "MessageSquareCode",
			},
		],
	},
	whyBetter: {
		heading: "Why Roo's PR Reviewer is different",
		features: [
			{
				title: "Bring your own key, get uncompromised reviews",
				paragraphs: [
					"Most AI review tools use fixed pricing, which means they skimp on tokens to protect their margins. That leads to shallow analysis and missed issues.",
					"With Roo, you bring your own API key. We optimize prompts for depth, not cost-cutting, so reviews focus on real problems like business logic, security vulnerabilities, and architectural issues.",
				],
				icon: "Blocks",
			},
			{
				title: "Advanced reasoning that understands what matters",
				description:
					"We leverage state-of-the-art reasoning models with sophisticated workflows: diff analysis, context gathering, impact mapping, and contract validation. This catches the subtle bugs that surface-level tools miss—misunderstood requirements, edge cases, and integration risks.",
				icon: "ListChecks",
			},
			{
				title: "Repository-aware, not snippet-aware",
				description:
					"Roo analyzes your entire codebase context—dependency graphs, code ownership, team conventions, and historical patterns. It understands how changes interact with existing systems, not just whether individual lines look correct.",
				icon: "BookMarked",
			},
		],
	},
	cta: {
		heading: "Ready for better code reviews?",
		description: "Start finding the issues that matter with AI-powered reviews built for depth, not cost-cutting.",
		buttonText: "Start 14-day Free Trial",
	},
}
