import { type AgentPageContent } from "@/app/shared/agent-page-content"

// Workaround for next/image choking on these for some reason
import hero from "/public/heroes/agent-reviewer.png"

// Re-export for convenience
export type { AgentPageContent }

export const content: AgentPageContent = {
	agentName: "PR Reviewer",
	hero: {
		icon: "GitPullRequest",
		heading: "Get comprehensive code reviews that save you time, not tokens.",
		paragraphs: [
			"Regular AI code review tools cap model usage to protect their margins from fixed monthly prices. That leads to shallow prompts, limited context, and missed issues.",
			"Roo Code's PR Reviewer flips the script: you bring your own key and leverage it to the max – to find real issues, increase code quality and keep your pull request queue moving.",
		],
		image: {
			url: hero.src,
			width: 800,
			height: 474,
			alt: "Example of a code review generated by Roo Code PR Reviewer",
		},
		crossAgentLink: {
			text: "Works great with",
			links: [
				{
					text: "PR Fixer Agent",
					href: "/pr-fixer",
					icon: "Wrench",
				},
			],
		},
		cta: {
			buttonText: "Start 14-day Free Trial",
			disclaimer: "(cancel anytime)",
		},
	},
	howItWorks: {
		heading: "How It Works",
		steps: [
			{
				title: "1. Connect Your Repository",
				description:
					"Link your GitHub repository and configure which branches and pull requests should be reviewed.",
				icon: "GitPullRequest",
			},
			{
				title: "2. Add Your API Key",
				description:
					"Provide your AI provider API key and set your review preferences, custom rules, and quality standards.",
				icon: "Key",
			},
			{
				title: "3. Get Review Comments",
				description:
					"Every pull request gets detailed GitHub comments in minutes from a Roo Code agent highlighting issues and suggesting improvements.",
				icon: "MessageSquareCode",
			},
		],
	},
	whyBetter: {
		heading: "Why Roo's PR Reviewer is so much better",
		features: [
			{
				title: "Our agents, your provider keys",
				paragraphs: [
					"We orchestrate the review, optimize the hell out of the prompts, integrate with GitHub, keep you properly posted.",
					"We're thoughtful about token usage, but not incentivized to skimp to grow our margins.",
				],
				icon: "Blocks",
			},
			{
				title: "Advanced reasoning and workflows",
				description:
					"We optimize for state-of-the-art reasoning models and leverage powerful workflows (Diff analysis → Context Gathering → Impact Mapping → Contract checks) to produce crisp, actionable comments at the right level.",
				icon: "ListChecks",
			},
			{
				title: "Fully repository-aware",
				description:
					"Reviews traverse code ownership, dependency graphs, and historical patterns to surface risk and deviations, not noise.",
				icon: "BookMarked",
			},
		],
	},
	cta: {
		heading: "Stop wasting time.",
		description:
			"Give Roo Code's PR Reviewer your model key and turn painful reviews into a tangible quality advantage.",
		buttonText: "Start 14-day Free Trial",
	},
}
